
## 描述


[[@http___zotero.org_users_local_gXnyYX7A_items_JZVJ3IU8]]

> ## [Unhandled rejections](https://javascript.info/promise-error-handling#unhandled-rejections)

> What happens when an error is not handled? For instance, we forgot to append `.catch` to the end of the chain, like here:



> In case of an error, the promise becomes rejected, and the execution should jump to the closest rejection handler. But there is none. So the error gets “stuck”. There’s no code to handle it.

>In practice, just like with regular unhandled errors in code, it means that something has gone terribly wrong.

> What happens when a regular error occurs and is not caught by `try..catch`? The script dies with a message in the console. A similar thing happens with unhandled promise rejections.

> The JavaScript engine tracks such rejections and generates a global error in that case. You can see it in the console if you run the example above.

重點:
- 當rejected狀態的promise找不到對應的then方法或者catch方法來攔截其object來處理錯誤，那麼就會將該promise object包裝的內容以global error來拋出，來讓系統上的預設錯誤處理機制攔截並處理之

## 複習
#🧠 JavaScript : 在Promise API時代中，若Promise內部執行的任務或者排程的任務拋出錯誤的話，系統會如何處理? (請考量到是否有Promise API語法所建立的錯誤處理)  ->->-> `首先會自動包裝成rejected狀態的promise object，然後找尋後面chain結構上是否存在then方法或者catch方法來處理錯誤處理，若沒有的話，那麼就會以正常拋出錯誤的形式來讓系統上的預設錯誤處理來攔截進行處理。`
<!--SR:!2023-06-12,35,250-->





#🧠 JavaScript : 以下p1為包裝特定任務的Promise object，若註冊後的事件處理拋出錯誤的話，那麼最後會如何執行![https://res.cloudinary.com/dqfxgtyoi/image/upload/v1681735097/blog/javascript/promise/Zalgo/promise-with-error-handler_vecbs1.png](https://res.cloudinary.com/dqfxgtyoi/image/upload/v1681735097/blog/javascript/promise/Zalgo/promise-with-error-handler_vecbs1.png) ->->-> `將拋出的錯誤包裝成rejected狀態的promise object，然後以該object來執行catch進行錯誤處理`
<!--SR:!2023-07-18,55,250-->


#🧠 JavaScript : 以下p1為包裝特定任務的Promise object，若註冊後的事件處理拋出錯誤的話，那麼最後會如何執行![https://res.cloudinary.com/dqfxgtyoi/image/upload/v1681735097/blog/javascript/promise/Zalgo/promise-without-error-handler_avjoze.png](https://res.cloudinary.com/dqfxgtyoi/image/upload/v1681735097/blog/javascript/promise/Zalgo/promise-without-error-handler_avjoze.png) ->->-> `將拋出的錯誤包裝成rejected狀態的promise object，但由於後續沒catch或者then所構成的錯誤處理，這會使得該promise object轉變成正常的錯誤來讓系統上的預設錯誤處理來攔截並處理`
<!--SR:!2023-06-08,33,250-->

#🧠   JavaScript : 以下p1為包裝特定任務的Promise object，若註冊後的事件處理拋出錯誤的話，那麼最後會如何執行 ![https://res.cloudinary.com/dqfxgtyoi/image/upload/v1681740441/blog/javascript/promise/Zalgo/task-in-first-promise-without-error-handler_whihet.png](https://res.cloudinary.com/dqfxgtyoi/image/upload/v1681740441/blog/javascript/promise/Zalgo/task-in-first-promise-without-error-handler_whihet.png) ->->-> `將拋出的錯誤包裝成rejected狀態的promise object，但由於後續沒catch或者then所構成的錯誤處理，這會使得該promise object轉變成正常的錯誤來讓系統上的預設錯誤處理來攔截並處理`
<!--SR:!2023-06-19,39,250-->


---
Status: #🌱 
Tags:
[[Promise]]
Links:
References:
[[@http___zotero.org_users_local_gXnyYX7A_items_JZVJ3IU8]]